--- 
- hosts: 172.31.30.15
  become: yes 
  tasks: 
  - name: execute linux command on a specific node
    command: hostname -f 
    register: myfirsttaskresult

  

  - name: i want to display above tasks result here
    debug:
      msg: "{{myfirsttaskresult}}"



      







