--- 
- hosts: 172.31.30.15 
  become: yes 
  tasks: 
  - include_tasks: myfile.yml

  - name: i want to copy file from source to destination 
    copy: 
      src: mystatic 
      dest: /home/ubuntu/mystaticfile

  
    



