--- 
- hosts: 172.31.30.15 
  become: yes 
  tasks: 
  - name: i want to execute multi packages
    apt: 
      name: "{{ item }}"
      state: present 
    loops: 
      - git 
      - tree 
      - wget 





    