---
- hosts: all 
  become: yes
  tasks: 
  - name: i want to install web server 
    apt: 
     name: apache2
     status: present 

  - name: i want to start web server 
    apt: 
     name: apache2 
     status: started